### ISSUE TITLE
Add Database Migrations

### ISSUE THREAD

**Issue by alneberg** [ScilifelabDataCentre/dds_web#583]
Add migrations to create databse schema and to version control the schema. The main benefit is that migrations can alter a database which is already populated without having to recreate the entire database every time.

**Comment by alneberg** [comment]
Notes for myself when this will be implemented:

### FIrst time setting up migrations (only once, not for each developer)
Edit the docker-compose temporarily to get a interactive session:
```
    entrypoint: /bin/bash
    ...
    ports:
      - 127.0.0.1:5000:5000
    stdin_open: true # docker run -i
    tty: true        # docker run -t
```
Create the migrations directory and run docker compose:
```bash
mkdir migrations
docker-compose down
docker-compose -f docker-compose-migrations.TMP.yml up
```

Then log into the backend container and run:
```bash
flask db init
flask db migrate -m "Initial migration"
```

For migrations downstream (I think the initial one is fine) we need to review the migration script, in particular:
> The migration script needs to be reviewed and edited, as Alembic currently does not detect every change you make to your models.
> In particular, Alembic is currently unable to detect table name changes, column name changes, or anonymously named constraints.
